#!/usr/bin/env node
/**
 * Local release assembly — build installers on this machine and stage
 * them on a draft GitHub Release, without burning Actions minutes.
 *
 *   node scripts/release-local.mjs                   # linux + windows, draft, upload, latest.json
 *   node scripts/release-local.mjs --no-windows      # linux only
 *   node scripts/release-local.mjs --from-run 123456 # also pull a CI run's artifacts (macOS) in
 *   node scripts/release-local.mjs --skip-build      # just re-sync assets/feed from what's built
 *
 * What it can and can't build here:
 *   linux    — natively (deb / rpm / AppImage).
 *   windows  — cross-compiled NSIS installer via cargo-xwin + makensis.
 *   macos    — impossible off a Mac. Run the release workflow with
 *              `platforms: macos` (workflow_dispatch), then fold the
 *              artifacts in with --from-run <run id>.
 *
 * The draft this stages is identical to what CI's tag build produces —
 * same notes, same updater feed. Review it, click Publish; publishing
 * creates the tag, and the tag-triggered workflow sees latest.json is
 * already attached and skips the whole matrix (the `plan` job guard).
 *
 * Updater signing: uses ~/.tauri/tokori-updater.key unless
 * TAURI_SIGNING_PRIVATE_KEY is already exported.
 */

import { execFileSync, execSync } from "node:child_process";
import { existsSync, mkdtempSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const args = process.argv.slice(2);
const has = (f) => args.includes(f);
const opt = (f) => {
  const i = args.indexOf(f);
  return i >= 0 ? args[i + 1] : null;
};

const die = (msg) => {
  console.error(`✗ ${msg}`);
  process.exit(1);
};
const step = (msg) => console.log(`\n── ${msg} ${"─".repeat(Math.max(0, 60 - msg.length))}`);

const sh = (cmd, env = {}) =>
  execSync(cmd, { cwd: root, stdio: "inherit", env: { ...process.env, ...env } });
const out = (cmd, cmdArgs) =>
  execFileSync(cmd, cmdArgs, { cwd: root, encoding: "utf8" }).trim();

// ── Preflight ─────────────────────────────────────────────────────────
const version = JSON.parse(readFileSync(join(root, "src-tauri/tauri.conf.json"), "utf8")).version;
const tag = `v${version}`;
const repo = out("gh", ["repo", "view", "--json", "nameWithOwner", "--jq", ".nameWithOwner"]);

step(`release-local ${tag} → ${repo}`);
// The lockfile is generated by the CI-pinned npm (see release.yml) —
// an older local npm can't `npm ci` it, and a missing install fails
// deep inside `npm run tauri` with a confusing "tauri: not found".
if (!existsSync(join(root, "node_modules", ".bin", "tauri")))
  die("node_modules not installed here — run: npx -y npm@11.18.0 ci");
sh("node scripts/release-check.mjs"); // manifests agree + changelog entry

const dirty = out("git", ["status", "--porcelain"]);
if (dirty) {
  console.warn(
    `⚠ working tree is dirty (${dirty.split("\n").length} paths) — the binaries will include those changes. Commit first for a reproducible release.`,
  );
}

// Signing: without the key the updater can't verify the download.
const keyPath = join(homedir(), ".tauri", "tokori-updater.key");
const signEnv = {};
if (!process.env.TAURI_SIGNING_PRIVATE_KEY) {
  if (!existsSync(keyPath)) die(`updater key not found at ${keyPath} and TAURI_SIGNING_PRIVATE_KEY unset`);
  signEnv.TAURI_SIGNING_PRIVATE_KEY = keyPath;
  signEnv.TAURI_SIGNING_PRIVATE_KEY_PASSWORD = process.env.TAURI_SIGNING_PRIVATE_KEY_PASSWORD ?? "";
}

// ── Build ─────────────────────────────────────────────────────────────
const buildLinux = !has("--skip-build") && !has("--no-linux");
const buildWindows = !has("--skip-build") && !has("--no-windows");

if (buildLinux) {
  step("build linux (deb / rpm / AppImage)");
  sh("npm run tauri build -- --bundles deb rpm appimage", signEnv);
}

if (buildWindows) {
  const toolchainOk =
    ["makensis", "cargo-xwin"].every((t) => {
      try {
        out("which", [t]);
        return true;
      } catch {
        return false;
      }
    });
  if (!toolchainOk) {
    console.warn("⚠ skipping windows: needs makensis + cargo-xwin (see launch/RELEASING.md → Route 2)");
  } else {
    step("build windows (NSIS, cross-compiled via cargo-xwin)");
    sh(
      "npm run tauri build -- --runner cargo-xwin --target x86_64-pc-windows-msvc --bundles nsis",
      signEnv,
    );
  }
}

// ── Collect artifacts ─────────────────────────────────────────────────
// Only files whose name carries the current version — stale bundles from
// earlier versions share these directories. Honours CARGO_TARGET_DIR so
// a build from a clean worktree can share the main repo's cargo cache.
const targetDir = process.env.CARGO_TARGET_DIR ?? join(root, "src-tauri/target");
const bundleDirs = [
  "release/bundle/appimage",
  "release/bundle/deb",
  "release/bundle/rpm",
  "x86_64-pc-windows-msvc/release/bundle/nsis",
];

const files = [];
for (const dir of bundleDirs) {
  const abs = join(targetDir, dir);
  if (!existsSync(abs)) continue;
  for (const name of readdirSync(abs)) {
    if (name.includes(version) && statSync(join(abs, name)).isFile()) files.push(join(abs, name));
  }
}

// CI artifacts (macOS .dmg / .app.tar.gz — anything the run produced).
// Matched by extension, not version: the `.app.tar.gz` updater bundle
// is named after the product only (`Tokori.app.tar.gz`).
const ARTIFACT_RE = /\.(dmg|app\.tar\.gz|exe|msi|deb|rpm|AppImage)(\.sig)?$/;
const fromRun = opt("--from-run");
if (fromRun) {
  step(`download artifacts from run ${fromRun}`);
  const dl = mkdtempSync(join(tmpdir(), "tokori-run-"));
  sh(`gh run download ${fromRun} --repo ${repo} --dir ${JSON.stringify(dl)}`);
  const walk = (d) => {
    for (const name of readdirSync(d)) {
      const p = join(d, name);
      if (statSync(p).isDirectory()) walk(p);
      else if (ARTIFACT_RE.test(name)) files.push(p);
    }
  };
  walk(dl);
}

if (files.length === 0) die("no artifacts found for this version — build first (or drop --skip-build)");
step(`artifacts (${files.length})`);
for (const f of files) console.log(`  ${f.split("/").pop()}`);

// ── Draft release ─────────────────────────────────────────────────────
// Release notes lead with this version's CHANGELOG.md section, so the
// GitHub release page shows what actually changed, not just install
// boilerplate.
function changelogSection(v) {
  const lines = readFileSync(join(root, "CHANGELOG.md"), "utf8").split("\n");
  const start = lines.findIndex((l) => l.startsWith(`## [${v}]`));
  if (start < 0) return null;
  let end = lines.length;
  for (let i = start + 1; i < lines.length; i++) {
    // Next release section or the link-definition block ends ours.
    if (lines[i].startsWith("## [") || /^\[.+\]:/.test(lines[i])) {
      end = i;
      break;
    }
  }
  return lines.slice(start + 1, end).join("\n").trim();
}

const changes = changelogSection(version);
const notes = `${changes ? `${changes}\n\n` : ""}### Install
- **macOS:** download the \`.dmg\`, drag Tokori to /Applications.
- **Windows:** download the \`*-setup.exe\` installer and run it. It's unsigned for now, so the first launch shows SmartScreen — click **More info → Run anyway**.
- **Linux — Debian/Ubuntu:** \`sudo apt install ./tokori_*.deb\`
- **Linux — Fedora/RHEL:** \`sudo dnf install ./tokori-*.rpm\`
- **Linux — Arch:** \`yay -S tokori-bin\` (AUR), or use the portable \`.AppImage\` (\`chmod +x\` and run).
`;

step(`stage draft release ${tag}`);
let exists = true;
try {
  out("gh", ["release", "view", tag, "--repo", repo, "--json", "isDraft"]);
} catch {
  exists = false;
}
const notesFile = join(mkdtempSync(join(tmpdir(), "tokori-notes-")), "notes.md");
writeFileSync(notesFile, notes);
if (!exists) {
  // Draft on a not-yet-existing tag: GitHub materialises the tag only
  // when the draft is published — so a failed attempt costs nothing.
  sh(
    `gh release create ${tag} --repo ${repo} --draft ${version.includes("-") ? "--prerelease" : ""} --title ${JSON.stringify(`Tokori ${tag}`)} --notes-file ${JSON.stringify(notesFile)}`,
  );
} else {
  // Keep an existing draft's notes in sync with CHANGELOG.md.
  sh(`gh release edit ${tag} --repo ${repo} --notes-file ${JSON.stringify(notesFile)}`);
}
sh(`gh release upload ${tag} --repo ${repo} --clobber ${files.map((f) => JSON.stringify(f)).join(" ")}`);

// ── Updater feed (latest.json) ────────────────────────────────────────
// Built from the release's ACTUAL asset list, so it's correct no matter
// which mix of local + CI artifacts got uploaded, or across re-runs.
step("regenerate latest.json");
const assets = JSON.parse(
  out("gh", ["release", "view", tag, "--repo", repo, "--json", "assets"]),
).assets.map((a) => a.name);

const sigFor = (assetName) => {
  const local = files.find((f) => f.endsWith(`${assetName}.sig`));
  if (local) return readFileSync(local, "utf8").trim();
  if (assets.includes(`${assetName}.sig`)) {
    const dl = mkdtempSync(join(tmpdir(), "tokori-sig-"));
    sh(`gh release download ${tag} --repo ${repo} --pattern ${JSON.stringify(`${assetName}.sig`)} --dir ${JSON.stringify(dl)}`);
    return readFileSync(join(dl, `${assetName}.sig`), "utf8").trim();
  }
  return null;
};

const url = (name) => `https://github.com/${repo}/releases/download/${tag}/${encodeURIComponent(name)}`;
const platforms = {};
const wire = (asset, keys) => {
  const signature = sigFor(asset);
  if (!signature) {
    console.warn(`⚠ ${asset}: no .sig — leaving it out of the updater feed`);
    return;
  }
  for (const k of keys) platforms[k] = { url: url(asset), signature };
};

for (const name of assets) {
  if (name.endsWith(".AppImage")) wire(name, ["linux-x86_64"]);
  else if (name.endsWith("-setup.exe")) wire(name, ["windows-x86_64"]);
  // Universal macOS updater bundle serves both architectures.
  else if (name.endsWith(".app.tar.gz")) wire(name, ["darwin-x86_64", "darwin-aarch64"]);
}

const feed = {
  version,
  notes: `Tokori ${tag} — see the release page for details.`,
  pub_date: new Date().toISOString(),
  platforms,
};
const feedFile = join(mkdtempSync(join(tmpdir(), "tokori-feed-")), "latest.json");
writeFileSync(feedFile, `${JSON.stringify(feed, null, 2)}\n`);
sh(`gh release upload ${tag} --repo ${repo} --clobber ${JSON.stringify(feedFile)}`);

step("done");
console.log(`Draft staged: https://github.com/${repo}/releases  (tag ${tag})
Updater feed covers: ${Object.keys(platforms).join(", ") || "nothing yet"}
${platforms["darwin-x86_64"] ? "" : "macOS missing — run: gh workflow run release.yml -f platforms=macos\n  then: node scripts/release-local.mjs --skip-build --from-run <run id>\n"}Review the draft, then Publish — publishing creates the tag; the tag-triggered
workflow sees latest.json already attached and skips the build matrix.`);
